### ISSUE TITLE
Feature request: woff/woff2 support

### ISSUE THREAD

**Issue by Hextar** [cssninjaStudio/unplugin-fonts#16]
If I get it right it's only possible to import .ttf.

Would be great to support other formats as well.

**Comment by maciekgrzybek** [comment]
+1 for that :)

**Comment by darkphoenixff4** [comment]
Nah, woff/woff2 works, at least on local files.  The issue I'm running into is that the rules generated are backwards:

TTF -> WOFF -> WOFF2 -> Local

When it really should be the other way around.

**Comment by interactivespace** [comment]
> Nah, woff/woff2 works, at least on local files. The issue I'm running into is that the rules generated are backwards:
> 
> TTF -> WOFF -> WOFF2 -> Local
> 
> When it really should be the other way around.

I am not sure if this is the right way to do it, but src can also be an array. So it is possible to set the order. But I can't figure out how to put the local as first.

`    ViteFonts({
      custom: {
        display: 'swap',
        families:[
          {
            name:'Roboto',
            src: ['./src/fonts/roboto*woff2','./src/fonts/roboto*woff', './src/fonts/roboto*ttf'],
            local:'Roboto',
          }
        ],
      },
    }),
`

**Comment by stafyniaksacha** [comment]
Hi there!

This has been fixed in the [`v1.0.0`](https://github.com/cssninjaStudio/unplugin-fonts/releases/tag/v1.0.0)

Feel free to reopen the issue if it persists!
