### ISSUE TITLE
Fonts for nested routes are not loaded properly

### ISSUE THREAD

**Issue by taranek** [cssninjaStudio/unplugin-fonts#32]
Hey, thank you for a great plugin!
I'm having an issue when loading fonts from a nested route. Here's an example where you can reproduce the issue:
https://stackblitz.com/edit/vitejs-vite-font-plugin-bug?file=src%2FApp.tsx

Steps to reproduce:
 1. Go to `/a/b/c` route in the sandbox and refresh a page, check the network tab to see 404 error.
 
 I think the issue is caused by injecting a relative path instead of an absolute one as a `href` attribute in the link tag. I'll post a PR that fixes the issue soon.

**Comment by stafyniaksacha** [comment]
This will be fixed with #39

**Comment by stafyniaksacha** [comment]
Hi @taranek!

This has been fixed in the [`v1.0.0`](https://github.com/cssninjaStudio/unplugin-fonts/releases/tag/v1.0.0)

Feel free to reopen the issue if it persists!
