### ISSUE TITLE
Using with typescript

### ISSUE THREAD

**Issue by gsimone** [cssninjaStudio/unplugin-fonts#34]
Hey, awesome plugin!

Adding the virtual import leads to an unresolved import error from eslint:
```
Unable to resolve path to module 'virtual:fonts.css'.
```

Some plugins have a solution like this (from: https://www.npmjs.com/package/vite-plugin-virtual-plain-text )

```
// declaration.d.ts
/// <reference types="vite-plugin-virtual-plain-text/virtual-assets" />
```

Anything similar here?

**Comment by stafyniaksacha** [comment]
Hello @gsimone 

This feature has been included in the [`v1.0.0`](https://github.com/cssninjaStudio/unplugin-fonts/releases/tag/v1.0.0)

```json
{
  "compilerOptions": {
    "types": ["unplugin-fonts/client"]
  }
}
```

or 

```ts	
// declaration.d.ts
/// <reference types="unplugin-fonts/client" />
```
