### ISSUE TITLE
[Feature]: Support vite v6.0.0

### ISSUE THREAD

**Issue by 1Luc1** [cssninjaStudio/unplugin-fonts#76]
Vite v6.0.0 just got released. Support requested.
https://github.com/vitejs/vite/releases/tag/v6.0.0

**Comment by 1Luc1** [comment]
Since this the PR https://github.com/cssninjaStudio/unplugin-fonts/pull/77, which will close this feature, was already merged, I was wondering if there will be a new version? Or are there any other plans? @stafyniaksacha

**Comment by stafyniaksacha** [comment]
Hello @1Luc1 the v1.2.0 has been released!
